#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Maypole-Cache
version:      0.01
version_from: Cache.pm
installdirs:  site
requires:
    Maypole:                       1.4
    Cache::Cache:                  0
    Class::ISA:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
