# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Maypole-Cache
version:      1.1
version_from: Cache.pm
installdirs:  site
requires:
    Cache::Cache:                  0
    Class::ISA:                    0
    Maypole:                       1.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
